### ISSUE TITLE
Replace Browserify with Rollup or Webpack

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/starter-kit#109]
I know there's some preference towards Browserify, but given D3 now sort of relies on tree shaking to be easily used, it would probably be beneficial to replace it with something that does dead code removal, i.e., Rollup or Webpack. 

Mainly posting issue for the sake of discussion.

**Comment by tomgp** [comment]
I think D3 & tree shaking's a red herring here. The minified version of the library is like ~250k, ~65k gzipped -- not exactly small but neither is it outrageously large.

**Comment by callumlocke** [comment]
I'm not wedded to Browserify, it's just that it's fast and "just works". I rarely find myself having to deal with a Browserify-related problem. Whenever I use Rollup, I have to go and tweak its settings often (but still I do sometimes use it, it's nice in other ways). Webpack I don't have much experience with.

I agree with Tom that tree-shaking should not be a priority unless we're encountering problematic bundle sizes, which I don't think we are. I think the real world performance impact would be negligible in most cases. Obviously smaller bundles are better, I just don't think it should be the major driving factor here. If switching to a different bundler makes the build system faster and friendlier for devs, that's certainly worth looking at.

But on a more general note... I think Starter Kit is such a 'mature' and entrenched workflow tool now, it would be easier to try out alternative tooling outside it. And eventually replace Starter Kit with something new and nice, rather than incrementally improve it. There is very little I would want to preserve anyway.

**Comment by aendrew** [comment]
@tomgp @callumlocke Good points both. I've updating my [tree-shaking comparison repo](https://github.com/aendrew/tree-shaking-comparison) and gotten the following:

```bash
-rw-r--r--  1 aendrew  241K 21 Dec 12:09 jspm-bundle.min.js
-rw-r--r--  1 aendrew   96K 21 Dec 12:09 rollup-bundle.min.js
-rw-r--r--  1 aendrew  169K 21 Dec 12:09 webpack-bundle.min.js
-rw-r--r--  1 aendrew  236K 13 Jun 16:43 browserify-bundle.min.js
```

It might not be a perfect test — I load in the ES6 module version of D3 and then use Babelify to let Browserify be able to use ES6 modules — but ultimately the max savings is ~140kb for Rollup.

That said, Tom's point about it only being 64kb total after gzipping is well-taken; given most graphics projects tend to be pretty light in terms of external media (videos, photos, &c.) the weight of D3 isn't too big a factor.

How then should we encourage the team to use D3? As per Alan's question in Slack earlier today, should we just tell people not to bother with the microlib style of D3 coding (unless they're really only using, for example, `d3-scale` — or wanting D3 features provided in other ways. For example, Alan's question involved d3-request and d3-dsv, which could probably even be reduced to just d3-dsv given we polyfill `window.fetch`).

Closing for now.
